name: steps
on:
  push:
    branches: [ master ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: My first step
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Chad
        MIDDLE_NAME: Michael
        LAST_NAME: Crowell
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
  
